config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:new, :create]
  resources :addresses, only: [:new, :create, :update]

  resources :signups, only: [:index, :new, :create] do
    collection do
      get 'sms_confirmation'
      get 'complete'
    end
  end
 
  resources :users do
    collection do
      get 'logout'
      get 'profile'
      get 'personal'
      get 'card'
      get 'exhibit'
    end
  end

  resources :items do
    get 'pay_confirmation'
    get 'pay'
    get 'pay_complete'
    get 'delete_image'
  end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :redirect_root, except: :complete

  layout 'registration'

  def index
    render :index, layout: "signup"
  end
  
  def new
    @user = User.new
  end
  
  def sms_confirmation
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_name_kana] = user_params[:last_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:birth_day] = birthday_join
    session[:provider] = session[:provider]
    session[:uid] = session[:uid]
    @user = User.new
  end

  def create
    if session[:provider].present? && session[:uid].present?
      password = set_password
      @user= User.new(
        nickname: session[:nickname], 
        email: session[:email], 
        password: password, 
        password_confirmation: password, 
        last_name: session[:last_name], 
        first_name: session[:first_name], 
        last_name_kana: session[:last_name_kana], 
        first_name_kana: session[:first_name_kana], 
        birth_day: session[:birth_day], 
        tel: user_params[:tel]
        )
    else
      @user= User.new(
        nickname: session[:nickname], 
        email: session[:email], 
        password: session[:password], 
        password_confirmation: session[:password_confirmation], 
        last_name: session[:last_name], 
        first_name: session[:first_name], 
        last_name_kana: session[:last_name_kana], 
        first_name_kana: session[:first_name_kana], 
        birth_day: session[:birth_day], 
        tel: user_params[:tel]
        )
    end
    if @user.save
      sign_in User.find(@user.id) unless user_signed_in?
      redirect_to new_address_path
    else
      render :new
    end
  end

  def complete
  end

  private

  def redirect_root
    redirect_to root_path if user_signed_in?
  end

  def birthday_join
    date_year = params[:user]["birth_day(1i)"] 
    date_month = params[:user]["birth_day(2i)"]
    date_day = params[:user]["birth_day(3i)"]
    
    if date_year.empty? && date_month.empty? && date_day.empty?
      return
    end

    date = Date.new(date_year.to_i, date_month.to_i, date_day.to_i)
  end

  def set_password
    password = Devise.friendly_token.first(7)
    if password.match(/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i)
      return password
    else
      set_password
    end
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_day, :tel)
  end
  
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/complete.html.haml
.signup-wrapper
  .signup-header
    .header-logo
      =link_to root_path do
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"
    %nav.progress-bar.signup-bar
      %ol
        %li 
          %p 会員情報
          .progress-status.start.active.though
        %li 
          %p 電話番号認証
          .progress-status.active.though
        %li 
          %p お届け先住所入力
          .progress-status.active.though
        %li 
          %p 支払い方法
          .progress-status.active.though
        %li 
          %p.active 完了
          .progress-status.end.active.though.now
  .regisration-main
    %main.registration-main-container
      .registration-main-container__header 会員登録完了
      %section.registration-main-container__form
        .registration-main-container__form__content
          .complete-message
            ありがとうございます。
            %br
            会員登録が完了しました。
          = link_to root_path, class: "btn-default" do
            メルカリをはじめる
      .signup-banner
        = image_tag "signup-banner.png"

app/views/signups/index.html.haml
.regisration-main
  %main.registration-main-container
    .registration-main-container__header 新規会員登録
    %section.registration-main-container__form--signup
      .registration-main-container__form__content
        =link_to new_signup_path, class: "btn-default signup mail" do
          = fa_icon 'envelope-o', class: "signup-icon"
          メールアドレスで登録する
        = link_to "/users/auth/facebook", method: :post, class: "btn-default signup facebook" do
          = fa_icon 'facebook-official', class: "signup-icon"
          Facebookで登録する
        = link_to "/users/auth/google_oauth2", method: :post, class: "btn-default signup google" do
          = fa_icon 'google', class: "signup-icon"
          Googleで登録する
.signup-footer.signup
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path, class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari

app/views/signups/new.html.haml
.signup-wrapper
  .signup-header
    .header-logo
      =link_to root_path do
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"
    %nav.progress-bar.signup-bar
      %ol
        %li 
          %p.active 会員情報
          .progress-status.start.active
        %li 
          %p 電話番号認証
          .progress-status
        %li 
          %p お届け先住所入力
          .progress-status
        %li 
          %p 支払い方法
          .progress-status
        %li 
          %p 完了
          .progress-status.end
  .regisration-main
    %main.registration-main-container
      %h2.registration-main-container__header 会員情報登録
      %section.registration-main-container__form
        - if @user.errors.any?
          - unless @user.valid?
            - if errors = @user.errors.full_messages
              %ul.signup-error-message
                - errors.each do |error|
                  %li=error
        = form_for(@user, url: sms_confirmation_signups_path, html: {method: "get"}) do |f|
          .registration-main-container__form__content
            .registration-main-container__form__content__group
              %label ニックネーム
              %span.form-require 必須
              = f.text_field :nickname, placeholder: "例）メルカリ太郎", class: "input-default"
            .registration-main-container__form__content__group
              %label メールアドレス
              %span.form-require 必須
              = f.email_field :email, placeholder: "PC・携帯どちらでも可", autocomplete: "email",  class: "input-default"
              - if @omniauth.nil?
                .registration-main-container__form__content__group
                  %label パスワード
                  %span.form-require 必須
                  = f.password_field :password, placeholder: "7文字以上", class: "input-default"
                .registration-main-container__form__content__group
                  %label パスワード(確認)
                  %span.form-require 必須
                  = f.password_field :password_confirmation, placeholder: "7文字以上", class: "input-default"
            .registration-main-container__form__content__group
              %h3 本人確認
              %p
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .registration-main-container__form__content__group
              %div
                %label お名前(全角)
                %span.form-require 必須
              .half-content
                = f.text_field :last_name, placeholder: "例)山田", class: "input-default half"
                = f.text_field :first_name, placeholder: "例)彩", class: "input-default half"
            .registration-main-container__form__content__group
              %div
                %label お名前カナ(全角)
                %span.form-require 必須
              .half-content
                = f.text_field :last_name_kana, placeholder: "例)ヤマダ", class: "input-default half"
                = f.text_field :first_name_kana, placeholder: "例)アヤ", class: "input-default half"
            .registration-main-container__form__content__group
              %div
                %label 生年月日
                %span.form-require 必須
              .signup-select
                =fa_icon 'angle-down', class:"birth_day year"
                =fa_icon 'angle-down', class:"birth_day month"
                =fa_icon 'angle-down', class:"birth_day day"
                = raw sprintf(f.date_select(:birth_day, prompt: "--", use_month_numbers: true,start_year: Time.now.year, end_year: (Time.now.year - 100), date_separator: '%s'), "年", "月") + "日"
            %p.registration-caution
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
            .registration-main-container__form__content__group
              %p.registration-consensus
              「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします 
              =f.submit "次へ進む", class: "btn-default"
            -# = render "devise/shared/links"

app/views/signups/signup.html.haml
.regisration-main
  %main.registration-main-container
    .registration-main-container__header 新規会員登録
    %section.registration-main-container__form--signup
      .registration-main-container__form__content
        %button.btn-default.signup.mail
          = fa_icon 'envelope-o', class: "signup-icon"
          メールアドレスで登録する
        %button.btn-default.signup.facebook
          = fa_icon 'facebook-official', class: "signup-icon"
          Facebookで登録する
        %button.btn-default.signup.google
          = fa_icon 'google', class: "signup-icon"
          Googleで登録する
.signup-footer.signup
  %nav
    %ul
      %li
        %a プライバシーポリシー
      %li
        %a メルカリ利用規約
      %li
        %a 特定商取引に関する表記
  %a.signup-footer__logo{href: "#"}
    %img{src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"}
  %p &copy;2019 Mercari

app/views/signups/sms_confirmation.html.haml
.signup-wrapper
  .signup-header
    .header-logo
      =link_to root_path do
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"
    %nav.progress-bar.signup-bar
      %ol
        %li 
          %p 会員情報
          .progress-status.start.active.though
        %li 
          %p.active 電話番号認証
          .progress-status.active.though.now
        %li 
          %p お届け先住所入力
          .progress-status
        %li 
          %p 支払い方法
          .progress-status
        %li 
          %p 完了
          .progress-status.end
  .regisration-main
    %main.registration-main-container
      .registration-main-container__header 電話番号の確認
      %section.registration-main-container__form
        = form_for @user, url: signups_path, method: :post do |f|
          .registration-main-container__form__content
            .registration-main-container__form__content_group
              %label 携帯電話の番号
              = f.text_field :tel, placeholder: "携帯電話の番号を入力", maxlength: "11", classs: "input-default"
              %p.registration-consensus
              本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
              = f.submit "SMSを送信する", class: "btn-default"
              %p.registration-consensus
              ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。