config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:new, :create]
  resources :addresses, only: [:new, :create, :update]

  resources :signups, only: [:index, :new, :create] do
    collection do
      get 'sms_confirmation'
      get 'complete'
    end
  end
 
  resources :users do
    collection do
      get 'logout'
      get 'profile'
      get 'personal'
      get 'card'
      get 'exhibit'
    end
  end

  resources :items do
    get 'pay_confirmation'
    get 'pay'
    get 'pay_complete'
    get 'delete_image'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_KATAKANA_REGEX = /\A[ァ-ヶー－]+\z/

  validates :nickname, presence: true 
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { in: 7..128 }, format: { with: VALID_PASSWORD_REGEX }, confirmation: true  
  validates :password_confirmation, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :first_name_kana, presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :birth_day, presence: true
  validates :tel, presence: true, uniqueness: true, length: { maximum: 11 }, numericality: { only_integer: true}
   
  has_one :address, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  has_many :items
  has_many_attached :images
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
          password: Devise.friendly_token.first(7)
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

   def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token.first(7)
      )
    end
    return {user: user}
   end

   def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end
  

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      session[:provider] = @sns[:provider]
      session[:uid] = @sns[:uid]
      render template: "signups/new" 
    end
  end

  def failure
    redirect_to root_path and return
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
  # frozen_string_literal: true

  # class Users::RegistrationsController < Devise::RegistrationsController
  #    before_action :configure_sign_up_params, only: [:create]
  #    before_action :configure_account_update_params, only: [:update]

  #   def after_sign_up_path_for(resource)
  #     address_signups_path
  #   end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
#end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def logout
  end

  def profile
  end

  def personal
  end

  def card
  end
  
  def exhibit
    @item = Item.where(user_id: current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_mypage-main-tabs.html.haml
%section.mypage-content__main-tab-container
  %ul.mypage-content__tabs
    %li.mypage-content__tab.mypage-content__tab--active
      %h3
        = link_to '#' do
          お知らせ
    %li.mypage-content__tab
      %h3
        = link_to '#' do
          やることリスト
        
  .mypage-content__notification
    %ul.mypage-content__notification-list
      %li
        = link_to '#', class: 'mypage-content__item-link' do
          %figure
            = image_tag 'mercari_profile.png', size: '48x48'
          .mypage-content__item-body
            .mypage-content__item-text
              事務局から個別メッセージ「ログイン通知」
            %time
              %span
                2 時間前
      %li
        = link_to '#', class: 'mypage-content__item-link' do
          %figure
            = image_tag 'mercari_profile.png', size: '48x48'
          .mypage-content__item-body
            .mypage-content__item-text
              事務局から個別メッセージ「ログイン通知」
            %time
              %span
                3 時間前
        %li.mypage-content__go-list
          = link_to '#' do
            一覧を見る

app/views/users/shared/_mypage-second-tabs.html.haml
%section.mypage-content__second-tab-container
  %h2.mypage-content__tab-head 
    購入した商品
  %ul.mypage-content__tabs
    %li.mypage-content__tab.mypage-content__tab--active
      %h3
        = link_to '#' do
          取引中
    %li.mypage-content__tab
      %h3
        = link_to '#' do
          過去の取引
  .mypage-content__tab-content
    %ul.mypage-content__item-list
      %li.mypage-content__not-found-item
        取引中の商品がありません

app/views/users/shared/_mypage-side-bar.html.haml
.mypage-side-bar
  %nav.mypage-side-bar__nav
    %ul.mypage-side-bar__list
      %li
        = link_to users_path(current_user), class: 'mypage-side-bar__list-item' do
          マイページ
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          お知らせ
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          やることリスト
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          いいね！一覧
          = fa_icon 'chevron-right'
      %li
        = link_to new_item_path, class: 'mypage-side-bar__list-item' do
          出品する
          = fa_icon 'chevron-right'
      %li
        = link_to exhibit_users_path, class: 'mypage-side-bar__list-item' do
          出品した商品 - 出品中
          = fa_icon 'chevron-right'
      %li
        = link_to  '#', class: 'mypage-side-bar__list-item' do
          出品した商品 - 取引中
          = fa_icon 'chevron-right'
      %li
        = link_to  '#', class: 'mypage-side-bar__list-item' do
          出品した商品 - 売却済み
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          購入した商品 - 取引中
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          購入した商品 - 過去の取引
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          ニュース一覧
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          評価一覧
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          ガイド
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          お問い合わせ
          = fa_icon 'chevron-right'
    %h3.mypage-side-bar__nav-head
      メルペイ
    %ul.mypage-side-bar__list
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          残高・振込申請
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          ポイント
          = fa_icon 'chevron-right'
    %h3.mypage-side-bar__nav-head
      設定
    %ul.mypage-side-bar__list
      %li
        = link_to profile_users_path(current_user), class: 'mypage-side-bar__list-item' do
          プロフィール
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          発送元・お届け先住所変更
          = fa_icon 'chevron-right'
      %li
        = link_to card_users_path, class: 'mypage-side-bar__list-item' do
          支払い方法
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          メール/パスワード
          = fa_icon 'chevron-right'
      %li
        = link_to personal_users_path(current_user), class: 'mypage-side-bar__list-item' do
          本人情報
          = fa_icon 'chevron-right'
      %li
        = link_to '#', class: 'mypage-side-bar__list-item' do
          電話番号の確認
          = fa_icon 'chevron-right'
      %li
        = link_to logout_users_path, class: 'mypage-side-bar__list-item' do
          ログアウト
          = fa_icon 'chevron-right'