config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:new, :create]
  resources :addresses, only: [:new, :create, :update]

  resources :signups, only: [:index, :new, :create] do
    collection do
      get 'sms_confirmation'
      get 'complete'
    end
  end
 
  resources :users do
    collection do
      get 'logout'
      get 'profile'
      get 'personal'
      get 'card'
      get 'exhibit'
    end
  end

  resources :items do
    get 'pay_confirmation'
    get 'pay'
    get 'pay_complete'
    get 'delete_image'
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :category
  
  validates :name, presence: true, length:{maximum: 40}
  validates :introduction, presence: true, length:{maximum: 1000}
  validates :condition, presence: true
  validates :d_burden, presence: true
  validates :d_way, presence: true
  validates :prefecture_id, presence: true
  validates :d_date, presence: true
  validates :price, numericality:{only_integer:true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, message:"300〜9,999,999の値で入力してください" }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :redirect_signin, only: [:new, :pay_confirmation, :pay_complete] 
  before_action :buy_info, only: [:pay_confirmation, :pay_complete] 

  def index
    @mens_items = Item.where(category_id: "2").order('created_at DESC').limit(10)
    @book_items = Item.where(category_id: "5").order('created_at DESC').limit(10)
    @kaden_items = Item.where(category_id: "8").order('created_at DESC').limit(10)
  end

  def new
    @item = Item.new
    render :new, layout: "signup"
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を出品しました"
      redirect_to :root
    else
      render :new
    end
  end

  def pay_confirmation
    card_info
    render :pay_confirmation, layout: "signup"
  end

  def pay
    @item = Item.find(params[:item_id])
    @card = current_user.card

    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy'
      )
      redirect_to item_pay_complete_path
    else
      flash[:purchase] = '購入エラー'
      render :pay_confirmation
    end

  end

  def pay_complete
    card_info
    render :pay_complete, layout: "signup"
  end

  def show
    @item = Item.find(params[:id])
    @images = @item.images.order(id: "DESC")
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy if item.user_id == current_user.id
    flash[:notice] = "商品を削除しました"
    redirect_to :root
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.user.id == current_user.id
      item.update(item_params)
    end
    flash[:notice] = "商品の更新をしました"
    redirect_to :root
  end


def delete_image
  item = Item.find(params[:item_id])
  images = item.images.attachments
  image = images.find(params[:keyword])
  image.purge
end


  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :condition, :d_burden, :d_way, :d_date,:prefecture_id, :price,:category_id,images: []).merge(user_id: current_user.id)
  end

  def buy_info
    @item = Item.find(params[:item_id])
    @address = current_user.address
    @image = @item.images[-1]
  end

  def card_info
    @card = current_user.card
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @card = customer.cards.retrieve(@card.card_id)
    return @card
  end

  def redirect_signin
    flash[:alert] = "ログインが必要です"
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.sell-main
  .sell-container
    .sell-container__inner
      %h2.sell__head 商品の情報を入力
      .sell-form
        = form_with(model: @item, local: true) do |f|
          = render "layouts/error-messages", model: @item
          .sell-upload__box
            %h3.sell-upload__head
              出品画像
              %span.form-require 必須
            %p 最大5枚までアップロード出来ます
            .sell-upload__image-box
              #preview
                - @item.images.each_with_index do |image, index|
                  .image-dropbox{data: {image: "#{image.id}"}}
                    = image_tag image
                    .delete-button 削除

              %label.input-zone
                = f.file_field :images, class: "sell-upload__file" , multiple: true
                .visible-pc
                  :preserve
                    クリックしてファイルをアップロード
    
          .sell-content
            .form-group
              %label 商品名
              %span.form-require 必須
              %div
              = f.text_field :name, class: "input-box", placeholder: "商品名(必須40文字まで)"
            .form-group
              %label 商品の説明
              %span.form-require 必須
              %div
              = f.text_area :introduction, class: "text-box", row:5, placeholder: "商品の説明(必須1,000文字以内)(色、素材、重さ、定価、注意点など) 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。"
          
          .sell-content.clearfix
            %h3.sell-sub__head
              商品の詳細
              %a.question ?
            .sell-form__box
              .form-group
                %label カテゴリー
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "---"},class: "select-bar"

              
              .form-group
                %label 商品の状態
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :condition, [["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"], ["目立った傷や汚れあり", "目立った傷や汚れあり"], ["やや傷や汚れあり", "やや傷や汚れあり"], [" 傷や汚れあり", " 傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]] ,{prompt: "---"},class: "select-bar"

          .sell-content.clearfix
            %h3.sell-sub__head
              配送について
              %a.question ?
            .sell-form__box
              .form-group#select_burden
                %label 配送料の負担
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :d_burden,[["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]],{prompt: "---"},class: "d_burden select-bar"

              .form-group#d_way
                %label 配送の方法
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :d_way,[@item.d_way],{prompt: "---"},class: "d_burden select-bar", name: "item[:d_way]"

              .form-group
                %label 発送元の地域
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "---"},class: "select-bar"
          
              .form-group
                %label 発送までの日数
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :d_date,[["1~2日で発送", "1~2日で発送"], ["2~3日で発送","2~3日で発送"],["4~7日で発送", "4~7日で発送"]],{prompt: "---"},class: "select-bar"
            
          .sell-content.clearfix
            %h3.sell-sub__head
              販売価格(300~9,999,999)
              %a.question ?
            .sell-form__box
              %ul.sell-price
                %li.form-group
                  .price-bar
                    %label.l-left
                      価格
                      %span.form-require 必須
                    %label.l-right.sell-price__input
                      .yen
                        ¥
                      = f.text_field :price, class: "input-price", placeholder: "例) 300"
                  %li.price-bar
                    %label.l-left
                      販売手数料(10%)
                    %label.l-right#display-fee
                      −
                  %li.price-bar.bold
                    %label.l-left
                      販売利益
                    %label.l-right#display-profit
                      −
        
          .sell-content
            .caution
              %p
                =link_to "禁止されている出品","#",{class: "caution-link"}
                、
                =link_to "行為", "#",{class: "caution-link"}
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合は誤記載ください。
                =link_to "偽ブランドの販売", "#",{class: "caution-link"}
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                =link_to "加盟店規約", "#",{class: "caution-link"}
                に同意したことになります。


            = f.submit "変更する", class: "sell-button red-button"
            = link_to root_path, class: "sell-button gray-button" do
              もどる
            %button{action: item_delete_image_path(@item), id:"image_delete", style: "display:none"}

.signup-footer
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path ,class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari

app/views/items/index.html.haml
.default-container
  = render 'layouts/header'
  .notifications
    = flash[:notice]
  .toppage-content
    %section.camp-keyvisual
      %h2
        =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/featured/camp/index/index_keyvisual.png?465897195")
    .item__content
      %h2.item__content__header
        人気のカテゴリー
      .item__box
        .item__box--search
          .item__box--search-genre
            メンズ
          .item__box--search-genre
            家電・スマホ・カメラ
          .item__box--search-genre
            本・音楽・ゲーム

    .item__main
      .item__main__genre
        %h3.item__main__genre--name
          メンズ新着アイテム
        .item__main__genre--sub
          = link_to "もっと見る", href: ""
      .items-box-content.clearfix.category-brand-list
        - @mens_items.each do |item|
          %section.items-box
            = link_to item_path(item) do
              .items-box-photo
                = image_tag item.images[-1] if item.images.present?
              .items-box-body
                %h3.items-box-name.font-2
                  = item.name
                .items-box-num
                  .items-box-price.font-5
                    ="￥#{item.price.to_s(:delimited)}"
    .item__main
      .item__main__genre
        %h3.item__main__genre--name
          家電・スマホ・カメラ新着アイテム
        .item__main__genre--sub
          = link_to "もっと見る", href: ""
      .items-box-content.clearfix.category-brand-list
        - @kaden_items.each do |item|
          %section.items-box
            = link_to item_path(item) do
              .items-box-photo
                = image_tag item.images[-1] if item.images.present?
              .items-box-body
                %h3.items-box-name.font-2
                  = item.name
                .items-box-num
                  .items-box-price.font-5
                    ="￥#{item.price.to_s(:delimited)}"
    .item__main
      .item__main__genre
        %h3.item__main__genre--name
          本・音楽・ゲーム新着アイテム
        .item__main__genre--sub
          = link_to "もっと見る", href: ""
      .items-box-content.clearfix.category-brand-list
        - @book_items.each do |item|
          %section.items-box
            = link_to item_path(item) do
              .items-box-photo
                = image_tag item.images[-1] if item.images.present?
              .items-box-body
                %h3.items-box-name.font-2
                  = item.name
                .items-box-num
                  .items-box-price.font-5
                    ="￥#{item.price.to_s(:delimited)}"
=render 'layouts/footer'

app/views/items/new.html.haml
.sell-main
  .sell-container
    .sell-container__inner
      %h2.sell__head 商品の情報を入力
      .sell-form
        = form_with(model: @item, local: true) do |f|
          = render "layouts/error-messages", model: @item
          .sell-upload__box
            %h3.sell-upload__head
              出品画像
              %span.form-require 必須
            %p 最大5枚までアップロード出来ます
            .sell-upload__image-box
              #preview
              %label.input-zone
                = f.file_field :images, class: "sell-upload__file" , multiple: true
                .visible-pc
                  :preserve
                    クリックしてファイルをアップロード
    
          .sell-content
            .form-group
              %label 商品名
              %span.form-require 必須
              %div
              = f.text_field :name, class: "input-box", placeholder: "商品名(必須40文字まで)"
            .form-group
              %label 商品の説明
              %span.form-require 必須
              %div
              = f.text_area :introduction, class: "text-box", row:5, placeholder: "商品の説明(必須1,000文字以内)(色、素材、重さ、定価、注意点など) 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。"
          
          .sell-content.clearfix
            %h3.sell-sub__head
              商品の詳細
              %a.question ?
            .sell-form__box
              .form-group
                %label カテゴリー
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "---"},class: "select-bar"

              .form-group
                %label 商品の状態
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :condition, [["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"], ["目立った傷や汚れあり", "目立った傷や汚れあり"], ["やや傷や汚れあり", "やや傷や汚れあり"], [" 傷や汚れあり", " 傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]] ,{prompt: "---"},class: "select-bar"

          .sell-content.clearfix
            %h3.sell-sub__head
              配送について
              %a.question ?
            .sell-form__box
              .form-group#select_burden
                %label 配送料の負担
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :d_burden,[["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]],{prompt: "---"},class: "d_burden select-bar"
              
              .form-group
                %label 発送元の地域
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "---"},class: "select-bar"
          
              .form-group
                %label 発送までの日数
                %span.form-require 必須
                %div
                  .select-box
                    = fa_icon "chevron-down", class: "select-chevron"
                    = f.select :d_date,[["1~2日で発送", "1~2日で発送"], ["2~3日で発送","2~3日で発送"],["4~7日で発送", "4~7日で発送"]],{prompt: "---"},class: "select-bar"
            
          .sell-content.clearfix
            %h3.sell-sub__head
              販売価格(300~9,999,999)
              %a.question ?
            .sell-form__box
              %ul.sell-price
                %li.form-group
                  .price-bar
                    %label.l-left
                      価格
                      %span.form-require 必須
                    %label.l-right.sell-price__input
                      .yen
                        ¥
                      = f.text_field :price, class: "input-price", placeholder: "例) 300"
                  %li.price-bar
                    %label.l-left
                      販売手数料(10%)
                    %label.l-right#display-fee
                      −
                  %li.price-bar.bold
                    %label.l-left
                      販売利益
                    %label.l-right#display-profit
                      −
        
          .sell-content
            .caution
              %p
                =link_to "禁止されている出品","#",{class: "caution-link"}
                、
                =link_to "行為", "#",{class: "caution-link"}
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合は誤記載ください。
                =link_to "偽ブランドの販売", "#",{class: "caution-link"}
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                =link_to "加盟店規約", "#",{class: "caution-link"}
                に同意したことになります。


            = f.submit "出品する", class: "sell-button red-button"
            = link_to root_path, class: "sell-button gray-button" do
              もどる


.signup-footer
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path ,class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari

app/views/items/pay_complete.html.haml
.purchase-main
  %main.purchase-main-container
    .purchase-main-container__delivery-info
      %p 
        %span
          発送をお待ちください 
        %br 
        出品者からの発送通知をお待ちください
    .purchase-main-container__header 購入が完了しました
    %section.purchase-main-container__content
      .purchase-main-container__content__item
        .purchase-main-container__content__item__inner
          =image_tag @image, class: "purchase-main-container__content__item__inner__image"
          %p.purchase-main-container__content__item__inner__name
            = @item.name
        %form.purchase-main-container__content__item__form
          .purchase-main-container__content__item__form
            .purchase-main-container__content__item__form__price
              .yen-price 
                ￥
                = @item.price.to_s(:delimited)
                %span 送料込み
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 配送先
            %address
              〒
              = @address.postal_code.to_s.insert(3, '-')
              %br
              = @address.area
              = @address.city
              = @address.address
              %br
              = @address.d_last_name
              = @address.d_first_name
            .purchase-main-container__content__user-info__inner__fix 
              = link_to "#" do
                変更する＞
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 支払い方法
            **** **** ****
            = @card.last4
            %br
            - if @card.exp_month < 10
              = "0#{@card.exp_month.to_s}"
            - else
              = @card.exp_month
            \/ 
            = @card.exp_year % 100
          .purchase-main-container__content__user-info__inner__fix 
          .purchase-main-container__content__user-info__inner__fix 
            = link_to "#" do
              変更する＞
.signup-footer.signup
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path, class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari

app/views/items/show.html.haml
= render 'layouts/header'
%main
  .items-wrapper
    %section.item__box-container
      %h1.item__name 
        = @item.name
      .item__main-content.clearfix
        .item__main__content
          .owl-carousel.owl-loaded.owl-drag
            .owl-stage-outer
              .owl-item
                .owl-item-inner.is-higher-height
                  .owl-lazy
                    - @images.each do |image|
                      = image_tag image if @item.images.present?
          .item__samjej
            .owl-dots
              .owl-dot
                %span
                .owl-dot-inner
                  .is-higher-height
                    - @images.each do |image|
                      = image_tag image if @item.images.present?
        %table.item__detail__table
          %tbody
            %tr
              %th 出品者
              %td
                =link_to user_path(@item.user) do
                  = @item.user.nickname
                %div
                  .item__detail__table__user
                    %i.icon-good
                      = fa_icon "smile-o"
                    %span 30
                  .item__detail__table__user
                    %i.icon-normal
                      = fa_icon "meh-o"
                    %span 0
                  .item__detail__table__user
                    %i.icon-bad
                      = fa_icon "frown-o"
                    %span 0
            %tr
              %th カテゴリー
              %td
                = link_to "#" do
                  = @item.category.name
            %tr
              %th ブランド
              %td
            %tr
              %th 商品の状態
              %td
                = @item.condition
            %tr
              %th 配送料の負担
              %td 
                = @item.d_burden
            %tr
              %th 配送の方法
              %td
                = @item.d_way
            %tr
              %th 配送元地域
              %td
                = Prefecture.find(@item.prefecture_id)[:name] 
            %tr
              %th 発送日の目安
              %td 
                = @item.d_date
      .item__price__box
        %span.item__price__box__price 
          = "¥#{@item.price.to_s(:delimited)}"
        %span.item__price__box__tax (税込)
        %span.item__price__box__fee 送料込み
      - if user_signed_in? && @item.user.id == current_user.id
        .text-center
          = link_to edit_item_path,method: :get,class: "item-select-btn" do
            この商品を編集する 
          = link_to item_path,method: :delete,data:{confirm: "本当に削除しますか？"}, class: "item-select-btn item-delete-btn" do
            この商品を削除する
      - else
        %section.visible-sp
          .item-btn-float-area
            =link_to item_pay_confirmation_path(@item), class:'item-buy-btn' do
              購入画面に進む
      %p.item-description-inner
        = @item.introduction

      .product-button-container.clearfix
        .product-button-left
          .product-button-like
            %button{type: "button", name: "like!", class: "product-button"}
              = fa_icon "heart"
              %span.fade-in-down いいね!
              %span.fade-in-down 0
        .product-button__report
          = link_to "", class: "product-button__report" do
            = fa_icon "flag"
            %span.fade-in-down 不適切な商品の報告            
        .product-button-right
          = link_to 'https://www.mercari.com/jp/safe/description/', target: "_blank", class: "safe-description" do
            = fa_icon "lock"
            あんしん・あんぜんへの取り組み
  .item__message
    .item__message__container
    .item__message__content
      %form.item__message__content-form{action: "", method: "POST"}
        %input{name: "__csrf_value", type: "hidden", value: "00adefeae53b9e1902b52ff10f47a8d98a5177ca4ae205a549780bc2621e9abb5cefa45ac2f844e9b477215706423ea6b5ca8ec770d4ca82c43e2706dbbb088e6"}/
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %input{name: "item_id", type: "hidden", value: "m70040871468"}/
        %input{name: "redirect_url_key", type: "hidden", value: "item_detail"}/
        %textarea.textarea-default{name: "body", type: "text", value: ""}
        %button.message-btn-gray{type: "submit"}
          %span コメントする
  %ul.nav__item
    %li
      =link_to "#", class:'nav__item__prev' do
        .nav__item__arrow-left
          = fa_icon 'arrow-left', class: "icon_arrow-left"
        前の商品
    %li
      =link_to "#", class:'nav__item__next' do
        次の商品
        .nav__item__arrow-right
          = fa_icon 'arrow-right', class: "icon_arrow-right"
  .item__social
    %ul.item__social__box
      %li
        = link_to "#", target: "_blank", class: 'share-btn' do
          .icon-facebook
            = fa_icon 'facebook', class: "icon_facebook"
      %li
        = link_to "#", target: "_blank", class: 'share-btn' do
          .icon-twitter
            = fa_icon 'twitter', class: "icon_twitter"
      %li
        = link_to "#", target: "_blank", class: 'share-btn' do
          .icon-pinterest
            = fa_icon 'pinterest', class: "icon_pinterest"
  %nav.bread-crumbs.pos-bottom
    - breadcrumb :show_item, @item 
    = render "layouts/breadcrumbs"
%aside
  .app__banner
    .app__banner__mine
      .app__banner__mine__inner
        .app__banner__mine__inner_flm
          %h2 スマホでかんたんフリマアプリ
        .app__banner__mine__inner_doun
          %p 今すぐ無料ダウンロード！
        .app__banner__mine__inner_icon
          %ul.image__link
            %li
              = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?465897195", width:'68', alt:"")
            %li
              = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?465897195", width:'133', height:'40', alt:"")
            %li
              = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?465897195", width:'133', height:'40', alt:"")
      %figure
        = link_to image_tag("sumaho.png", height:'300', width:'260', alt:"")
%footer
  .global-footer
    %nav.clearfix
      .footer-cell
        %h2.footer-head メルカリについて
        %ul
          %li.footer__contents__links_link
            = link_to "会社概要（運営会社）", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "採用情報", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "プレスリリース", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "公式ブログ", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "メルカリロゴ利用ガイドライン", {}, style: "color:#fff"
        .footer-icon
          %li
            = link_to "", class: "footer-social-link" do
              = fa_icon 'twitter', class: "icon_twitter"
          %li
            = link_to "", class: "footer-social-link" do
              = fa_icon 'facebook', class: "icon_facebook"
      .footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul
          %li.footer__contents__links_link
            = link_to "メルカリガイド", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "楽々メルカリ便", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "ゆうゆうメルカリ便", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "大型メルカリ便", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "車体取引ガイド", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "メルカリあんしん・あんぜん宣言！", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "偽ブランド品撲滅への取り組み", {}, style: "color:#fff"
          %li.footer__contents__links_link
            = link_to "メルカリボックス", {}, style: "color:#fff"
      .footer-cell.full-width
        %h2.footer-head プライバシーと利用規約
        .inner-footer-cell
          %ul
            %li.footer__contents__links_link
              = link_to "プライバシーポリシー", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "メルカリ利用規約", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "あんしんスマホサポート制度に関する利用規約", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "コンプライアンスポリシー", {}, style: "color:#fff"
      .footer-cell.full-width
        %h2.footer-head 
        .inner-footer-cell
          %ul
            %li.footer__contents__links_link
              = link_to "個人データの安全管理にかかる基本方針", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "特定商取引に関する表記", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "資金決済法に基づく表示", {}, style: "color:#fff"
            %li.footer__contents__links_link
              = link_to "法令順守と犯罪仰止のために", {}, style: "color:#fff"
      .footer-cell.footer-nav-lang
        %h2.footer-head 国
        %ul
          %li
            = link_to"#" do
              日本
          %li
            =link_to"#" do
              United States         
    .footer-bottom
      .footer-logo
        = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?465897195", height: '33', width: '124', href:"")  
      %span.footer-copyright
        %small © 2019 Mercari