config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:new, :create]
  resources :addresses, only: [:new, :create, :update]

  resources :signups, only: [:index, :new, :create] do
    collection do
      get 'sms_confirmation'
      get 'complete'
    end
  end
 
  resources :users do
    collection do
      get 'logout'
      get 'profile'
      get 'personal'
      get 'card'
      get 'exhibit'
    end
  end

  resources :items do
    get 'pay_confirmation'
    get 'pay'
    get 'pay_complete'
    get 'delete_image'
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  layout 'registration'
  
  def new
    card = Card.where(user_id: current_user.id)
    if card.exists?
      redirect_to root_path
    else
      @card = Card.new
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to complete_signups_path
      else
        redirect_to action: :create
      end
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.signup-wrapper
  .signup-header
    .header-logo
      =link_to root_path do
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"
    %nav.progress-bar.signup-bar
      %ol
        %li 
          %p 会員情報
          .progress-status.start.active.though
        %li 
          %p 電話番号認証
          .progress-status.active.though
        %li 
          %p お届け先住所入力
          .progress-status.active.though
        %li 
          %p.active 支払い方法
          .progress-status.active.though.now
        %li 
          %p 完了
          .progress-status.end
  .regisration-main
    %main.registration-main-container
      .registration-main-container__header 支払い方法
      %section.registration-main-container__form
        - if @card.errors.any?
          - unless @card.valid?
            - if errors = @card.errors.full_messages
              %ul.signup-error-message
                - errors.each do |error|
                  %li=error
        = form_with url: cards_path, method: :post, html: { id: "card_form" } do |f|
          .registration-main-container__form__content
            .registration-main-container__form__content_group
              = f.label "カード番号"
              %span.form-require 必須
              = f.text_field :card_number, placeholder: "半角数字のみ", autocomplete: 'off', maxlength: "16", class: "input-default number", name: "number"
            .registration-main-container__form__content__group
              %div
                = f.label "有効期限"
                %span.form-require 必須
              .signup-select
                .signup-select__content.card
                  =fa_icon 'angle-down'
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{:prompt => "---" },class: "select-default exp_month", name: "exp_month"
                %span 月
                .signup-select__content.card
                  =fa_icon 'angle-down'
                  = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{:prompt => "---"},class: "select-default exp_year", name: "exp_year"
                %span 年
            .registration-main-container__form__content__group
              =f.label "セキュリティコード"
              %span.form-require 必須
              = f.text_field :cvc, placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", class: "input-default cvc", name: "cvc"
            
              = f.submit "次へ進む", class: "btn-default", id: "card_submit"
              %script{:src => "https://js.pay.jp/", :type => "text/javascript"}

app/views/cards/pay_complete.html.haml
.purchase-main
  %main.purchase-main-container
    .purchase-main-container__delivery-info
      %p 
        %span
          発送をお待ちください 
        %br 
        出品者からの発送通知をお待ちください
    .purchase-main-container__header 購入が完了しました
    %section.purchase-main-container__content
      .purchase-main-container__content__item
        .purchase-main-container__content__item__inner
          =image_tag "m70040871468_1.jpg", class: "purchase-main-container__content__item__inner__image"
          %p.purchase-main-container__content__item__inner__name
            美品】初代 ゲームボーイ カスタム GAME BOY【1102】【美品】初代 ゲームボーイ カスタム GAME BOY【1102】【美品】初代 ゲームボーイ カスタム GAME BOY【1102】
        %form.purchase-main-container__content__item__form
          .purchase-main-container__content__item__form
            .purchase-main-container__content__item__form__price
              .yen-price 
                ￥8,600 
                %span 送料込み
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 配送先
            %address
              〒150-0041
              %br
              東京都 渋谷区 神南１丁目１８−２
              %br
              メルカリ 太郎
            .purchase-main-container__content__user-info__inner__fix 
              = link_to "#" do
                変更する＞
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 支払い方法
            **** **** ****4242
            %br
            12 / 20
          .purchase-main-container__content__user-info__inner__fix 
            = link_to "#" do
              変更する＞
.signup-footer.signup
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path, class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari

app/views/cards/pay_confirmation.html.haml
.purchase-main
  %main.purchase-main-container
    .purchase-main-container__header 購入内容の確認
    %section.purchase-main-container__content
      .purchase-main-container__content__item
        .purchase-main-container__content__item__inner
          =image_tag "m70040871468_1.jpg", class: "purchase-main-container__content__item__inner__image"
          %p.purchase-main-container__content__item__inner__name
            【美品】初代 ゲームボーイ カスタム GAME BOY【1102】【美品】初代 ゲームボーイ カスタム GAME BOY【1102】【美品】初代 ゲームボーイ カスタム GAME BOY【1102】
        %form.purchase-main-container__content__item__form
          .purchase-main-container__content__item__form
            .purchase-main-container__content__item__form__price
              .yen-price 
                ￥8,600 
                %span 送料込み
            =link_to "#", class: "btn-default point" do
              ポイントはありません
            %ul.purchase-main-container__content__item__form__pay
              %li.ja 支払い金額
              %li.yen-price ￥8,600
            =link_to "#", class: "btn-default purchase-decision" do
              購入する
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 配送先
            %address
              〒150-0041
              %br
              東京都 渋谷区 神南１丁目１８−２
              %br
              メルカリ 太郎
            .purchase-main-container__content__user-info__inner__fix 
              = link_to "#" do
                変更する＞
      .purchase-main-container__content__user-info
        .purchase-main-container__content__user-info__inner
          .purchase-main-container__content__user-info__inner__text
            %h3 支払い方法
            **** **** ****4242
            %br
            12 / 20
          .purchase-main-container__content__user-info__inner__fix 
            = link_to "#" do
              変更する＞
.signup-footer.signup
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー", "#"
      %li
        =link_to "メルカリ利用規約", "#"
      %li
        =link_to  "特定商取引に関する表記", "#"
  =link_to root_path, class: "signup-footer__logo" do
    =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?465897195", width: "100", height: "auto"
  %p &copy;2019 Mercari